blog/urls.py
from django.urls import path

from blog.views import PostDetailView
from blog.views import PostListView
from blog.views import PostCreateView
from blog.views import PostUpdateView
from blog.views import PostDeleteView


urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('posts/', PostListView.as_view(), name ='post_list'),
    path('post/<slug:slug>', PostDetailView.as_view(), name='post_detail'),
    path('posts/create', PostCreateView.as_view(), name='post_create'),
    path('posts/<slug:slug>/edit', PostUpdateView.as_view(), name='post_update'),
    path('posts/<slug:slug>/delete', PostDeleteView.as_view(), name='post_delete'),
]

hangboard/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include(('allauth.urls','allauth'), namespace='allauth')),
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('climber/', include(('climbers.urls','climbers'),namespace='climbers')),
    path('workouts/', include(('workouts.urls', 'workouts'),namespace='workouts')),
    path('ckeditor/', include(('ckeditor_uploader.urls','ckeditor'),namespace='ckeditor')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.utils.text import slugify
from django.utils import timezone
from django.db import models
from django_currentuser.db.models import CurrentUserField

from ckeditor.fields import RichTextField

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    slug = models.SlugField(max_length=150, unique=True)
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = CurrentUserField()

    def save(self, *args, **kwargs):
        self.slug = f'{slugify(self.title)}-{slugify(timezone.now().date())}'
        return super(Post, self).save(*args, **kwargs)

blog/views.py
from django.shortcuts import render
from django.urls import reverse

from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from blog.models import Post


class PostListView(ListView):
    model = Post
    template_name_suffix = '_list'
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post
    template_name_suffix = '_detail'
    context_object_name = 'post'


class PostCreateView(CreateView):
    model = Post
    fields = ('title', 'content')
    template_name_suffix = '_form'

    def get_success_url(self):
        return reverse('blog:post_detail', args=(self.object.slug,))


class PostUpdateView(UpdateView):
    model = Post
    fields = ('title', 'content')
    template_name_suffix = '_form'

    def get_success_url(self):
        return reverse('blog:post_detail', args=(self.object.slug,))


class PostDeleteView(DeleteView):
    model = Post
    template_name_suffix = '_delete'

    def get_success_url(self):
        return reverse('blog:post_list')

blog/templates/blog/post_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input type="submit" value="save" />
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <a href="{% url 'blog:post_update' slug=post.slug %}">Update</a>
    <h1>{{ post.title }}</h1>
    <p>{{ post.content|safe }}</p>
    <span>{{ post.author }}</span>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input type="submit">
    </form>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'main/base.html' %}

{% block content %}

    <a href="{% url 'blog:post_create' %}">Add Post</a>
    {% for post in posts %}
        <a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a>
        <a href="{% url 'blog:post_delete' slug=post.slug %}">Delete</a>
    {% endfor %}

{% endblock %}