blog/urls.py
from django.urls import path

from blog.views import PostDetailView
from blog.views import PostListView
from blog.views import PostCreateView
from blog.views import PostUpdateView
from blog.views import PostDeleteView


urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('posts/', PostListView.as_view(), name ='post_list'),
    path('post/<slug:slug>', PostDetailView.as_view(), name='post_detail'),
    path('posts/create', PostCreateView.as_view(), name='post_create'),
    path('posts/<slug:slug>/edit', PostUpdateView.as_view(), name='post_update'),
    path('posts/<slug:slug>/delete', PostDeleteView.as_view(), name='post_delete'),
]

climbers/urls.py
from django.urls import path, include
from climbers.views import profile_view
from climbers.views import preferences_view
from climbers.views import measurements_view

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('preferences/', preferences_view, name='preferences'),
    path('measurements/', measurements_view, name='measurements'),
]

hangboard/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include(('allauth.urls','allauth'), namespace='allauth')),
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('climber/', include(('climbers.urls','climbers'),namespace='climbers')),
    path('workouts/', include(('workouts.urls', 'workouts'),namespace='workouts')),
    path('ckeditor/', include(('ckeditor_uploader.urls','ckeditor'),namespace='ckeditor')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.urls import include

from main.views import home_view
from main.views import login_view

urlpatterns = [
    path('', home_view, name='home'),
    path('login', login_view, name='login'),
]

workouts/urls.py
from django.urls import path, include

from workouts.views.add import add_workout_set_view
from workouts.views.add import add_workout_view
from workouts.views.add import AddHangboardView
from workouts.views.add import add_hold_view

from workouts.views.add import AutoCompleteExerciseView
from workouts.views.add import AutoCompleteHangboardView
from workouts.views.add import AutoCompleteHoldTypeView
from workouts.views.add import AutoCompleteHoldView

from workouts.views.edit import edit_exercise_view

from workouts.views.get import WorkoutListView
from workouts.views.get import workout_detail_view
from workouts.views.get import hangboard_detail_view
from workouts.views.get import WorkoutSetDetailView
from workouts.views.get import ExerciseListView
from workouts.views.get import HangboardListView

urlpatterns = [
    path('', WorkoutListView.as_view(), name='workout_list'),
    path('exercises', ExerciseListView.as_view(), name='exercise_list'),
    path('hangboards', HangboardListView.as_view(), name='hangboard_list'),
    path('hangboards/hangboard=<int:hangboard_id>/', hangboard_detail_view, name='hangboard_detail'),

    path('add_workout', add_workout_view, name='add_workout'),
    path('add_hangboard', AddHangboardView.as_view(), name='add_hangboard'),
    path('hangboard=<int:hangboard_id>/add_hold', add_hold_view, name='add_hold'),

    path('autocomplete_exercise', AutoCompleteExerciseView.as_view(create_field='name'), name='autocomplete_exercise'),
    path('autocomplete_hold_type', AutoCompleteHoldTypeView.as_view(create_field='name'), name='autocomplete_hold_type'),
    path('autocomplete_hangboard', AutoCompleteHangboardView.as_view(create_field='name'), name='autocomplete_hangboard'),
    path('autocomplete_hold', AutoCompleteHoldView.as_view(create_field='name'), name='autocomplete_hold'),

    path('edit_exercise/<int:exercise_id>/', edit_exercise_view, name='edit_exercise'),

    path('workout=<int:workout_id>/', workout_detail_view, name='workout_detail'),
    path('workout=<int:workout_id>/workout_set=<int:workout_set_id>', WorkoutSetDetailView.as_view(), name='workout_set_detail'),
    path('workout=<int:workout_id>/add/', add_workout_set_view, name='add_workout_set'),
    path('workout=<int:workout_id>/add/previous=<int:previous>', add_workout_set_view, name='add_workout_set')
]

main/views.py
from django.shortcuts import render


def home_view(request):
    template_name = 'main/index.html'
    context = dict()
    context['title'] = 'Home'
    context['description'] = 'App for all things hangboarding'

    return render(request, context=context, template_name=template_name)


def login_view(request):
    template_name = 'main/login.html'
    context = dict()
    context['title'] = 'Login'
    context['description'] = 'Login'

    return render(request, context=context, template_name=template_name)

main/templates/main/base.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ title }}</title>
        <!-- Meta Tags -->
        <meta charset="UTF-8">
        <meta name="author" content="Marek Schir">
        <meta name="description" content="{{ description }}">

        <!-- Stylesheets -->
        <!--<link rel="stylesheet" href="{% static 'css/main.css' %}">-->

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="nav justify-content-center">
                <a class="nav-link" href="{% url 'home' %}">hangboard.io</a>
                <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'workouts:workout_list' %}">Workouts</a>
                    <a class="nav-link" href="{% url 'workouts:hangboard_list' %}">Hangboards</a>
                    <a class="nav-link" href="{% url 'climbers:profile' %}">Profile</a>
                    <a class="nav-link" href="{% url 'climbers:preferences' %}">Preferences</a>
                    <a class="nav-link" href="{% url 'climbers:measurements' %}">Measurements</a>
                    <a class="btn btn-primary" href="{% url 'allauth:account_logout' %}">Log Out</a>
                {% else %}
                    <a class="btn btn-primary"href="{% provider_login_url "google" %}">Log In</a>
                {% endif %}
            </nav>
            {% block header %}

            {% endblock %}
        </header>

        <div id="content" class="container container-fluid">

            {% block content %}

            {% endblock %}

        </div>

        <footer>

            {% block footer %}

            {% endblock %}

        </footer>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

        {% block javascript %}

        {% endblock %}
    </body>

</html>

main/templates/main/index.html
{% extends 'main/base.html' %}